remote_theme: kosatyi/sjt

navigation: true
projects: true

exclude:
  - .idea
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfil.lock
  - gulpfile.js

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

baseurl: /ipsp-js-sdk

brand: IPSP JS SDK
title: IPSP JS SDK
description: Alliance bank Payment System
logo: fondy.svg

author:
  name: Alliance bank Developer Team
  url: https://example.com/

toolbar:
  -
    name: Docs
    link: /docs/
  -
    name: Examples
    link: /examples/


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
